# Generated by Django 4.1 on 2023-05-08 17:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0004_alter_movie_budget_alter_movie_duration_and_more"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ("review",)},
        ),
        migrations.AddField(
            model_name="review",
            name="critic",
            field=models.ForeignKey(
                default="b2762811-eb45-4ab9-a883-80e420443294",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                default="b2762811-eb45-4ab9-a883-80e420443294",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="movies.movie",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="review",
            field=models.TextField(default="asdasdasd"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="spoilers",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="stars",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
