# Generated by Django 4.1 on 2023-05-08 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="stars",
            field=models.IntegerField(
                default=1,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message={"detail": "Not found."}
                    ),
                    django.core.validators.MaxValueValidator(
                        5, message={"detail": "Not found."}
                    ),
                ],
            ),
        ),
    ]
