# Generated by Django 4.1 on 2023-05-08 18:41

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0007_alter_review_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="spoilers",
            field=models.BooleanField(
                default=False, null=True, validators=[reviews.models.validate_stars]
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="stars",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
