# Generated by Django 4.1 on 2023-05-08 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Untitled", max_length=127)),
                ("duration", models.DurationField(default="1 days 01:00:00")),
                ("premiere", models.DateField(default="01/01/2023", max_length=127)),
                (
                    "budget",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("overview", models.TextField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
    ]
