# Generated by Django 4.1 on 2023-05-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.DurationField(default=None),
        ),
    ]
