# Generated by Django 4.1 on 2023-05-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_movie_budget_alter_movie_premiere_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="budget",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="premiere",
            field=models.DateField(max_length=127),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=127),
        ),
    ]
